import puppeteer from "puppeteer";
const calls = [];
const b = await puppeteer.launch({ executablePath:"C:/Program Files/Google/Chrome/Application/chrome.exe", headless:"new", args:["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width:1400, height:1000 });
p.on("response", r => { if (r.url().includes("/api/gemini")) calls.push(r.status()); });
await p.goto("http://localhost:3000", { waitUntil:"networkidle2", timeout:60000 });
await new Promise(r=>setTimeout(r,3200));
await p.evaluate(()=>document.querySelector("#sec-heritage .tilt-card").click());
await p.waitForFunction(()=>document.body.textContent.includes("PHOTO GALLERY"),{timeout:20000});
const click = (t)=>p.evaluate((txt)=>{const b=[...document.querySelectorAll("button")].find(n=>n.textContent.toLowerCase().includes(txt.toLowerCase()));if(b){b.click();return true}return false},t);
await click("PLAN VISIT");
await p.waitForFunction(()=>document.body.textContent.includes("CURRENT WEATHER"),{timeout:20000});
const before = calls.length;
await click("Ask Gemini for travel advice");
const ok = await p.waitForFunction(()=>document.body.textContent.includes("Quick tips"),{timeout:60000}).then(()=>true).catch(()=>false);
const panel = ok ? await p.evaluate(()=>{const t=document.body.innerText;const i=t.indexOf("Quick tips");return t.slice(Math.max(0,i-260), i+220)}) : "";
const adviceCalls = calls.slice(before);
console.log(ok && adviceCalls.includes(200) ? "PASS" : "FAIL", " weather advice from Gemini —", panel.replace(/\s+/g," ").slice(0,140));
console.log("advice call statuses:", adviceCalls.join(", "));
await b.close();
